name: 'StarClass'
description: 'Automatically cluster your starred GitHub repositories using semantic similarity'
author: 'gojiplus'

inputs:
  github-token:
    description: 'GitHub token with user scope to access starred repositories'
    required: true
  username:
    description: 'GitHub username (optional, defaults to token owner)'
    required: false
  cluster-mode:
    description: 'Clustering mode: auto, full, or assign'
    required: false
    default: 'auto'

outputs:
  clusters-json:
    description: 'Path to generated clusters JSON file'
    value: 'starred_repos_clusters.json'
  clusters-markdown:
    description: 'Path to generated clusters Markdown file'
    value: 'starred_repos_clusters.md'
  data-json:
    description: 'Path to raw repository data JSON file'
    value: 'starred_repos_data.json'
  changes-json:
    description: 'Path to repository changes tracking file'
    value: 'starred_repos_changes.json'
  repos-list-json:
    description: 'Path to starred repositories list file'
    value: 'starred_repos_list.json'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/scripts/requirements.txt
        
    - name: Fetch starred repositories
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.username }}
      run: python ${{ github.action_path }}/scripts/fetch_starred.py
        
    - name: Collect repository data
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.username }}
      run: python ${{ github.action_path }}/scripts/collect_data.py
      
    - name: Generate clusters
      shell: bash
      env:
        CLUSTER_MODE: ${{ inputs.cluster-mode }}
      run: python ${{ github.action_path }}/scripts/cluster_repos.py

branding:
  icon: 'star'
  color: 'blue'