name: Update Starred Repos Tags

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-tags:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/make_tags.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add starred_repos_tags.md
        git diff --staged --quiet || git commit -m "Update starred repos tags"
        git push